#!/usr/bin/env bash
set -euo pipefail

FINALIZATION_PROJECT=${FINALIZATION_PROJECT:?set FINALIZATION_PROJECT}
TRAINING_PROJECT=${TRAINING_PROJECT:?set TRAINING_PROJECT}
FORMAL_PROJECT=${FORMAL_PROJECT:-/root/autodl-tmp/CoFiTok/CoFiTok-internal}
PYTHON=${PYTHON:-/root/autodl-tmp/conda/envs/pf-vlm/bin/python}
CHECKPOINT_ROOT=${CHECKPOINT_ROOT:-/root/autodl-tmp/CoFiTok/checkpoints/generation}
SOURCE_OUTPUT_ROOT=${SOURCE_OUTPUT_ROOT:-$CHECKPOINT_ROOT/stability_full_data_100k_capacity_probe_250m_10k_v1}
FULL_OUTPUT_ROOT=${FULL_OUTPUT_ROOT:-$CHECKPOINT_ROOT/stability_capacity_full_300k_v1}

EXPECTED_TRAINING_SUPERVISOR_DEPLOYMENT_SHA256=${EXPECTED_TRAINING_SUPERVISOR_DEPLOYMENT_SHA256:?set EXPECTED_TRAINING_SUPERVISOR_DEPLOYMENT_SHA256}
EXPECTED_POSTEVAL_SUPERVISOR_DEPLOYMENT_SHA256=${EXPECTED_POSTEVAL_SUPERVISOR_DEPLOYMENT_SHA256:?set EXPECTED_POSTEVAL_SUPERVISOR_DEPLOYMENT_SHA256}
EXPECTED_TRAINING_LAUNCH_RECEIPT_SHA256=${EXPECTED_TRAINING_LAUNCH_RECEIPT_SHA256:?set EXPECTED_TRAINING_LAUNCH_RECEIPT_SHA256}
EXPECTED_FINAL_GATE_SHA256=${EXPECTED_FINAL_GATE_SHA256:?set EXPECTED_FINAL_GATE_SHA256}
EXPECTED_TRAINING_REVISION=${EXPECTED_TRAINING_REVISION:?set EXPECTED_TRAINING_REVISION}
EXPECTED_TRAINING_TREE=${EXPECTED_TRAINING_TREE:?set EXPECTED_TRAINING_TREE}
EXPECTED_TRAINING_BRANCH=${EXPECTED_TRAINING_BRANCH:?set EXPECTED_TRAINING_BRANCH}
EXPECTED_EVALUATION_REVISION=${EXPECTED_EVALUATION_REVISION:?set EXPECTED_EVALUATION_REVISION}
EXPECTED_EVALUATION_TREE=${EXPECTED_EVALUATION_TREE:?set EXPECTED_EVALUATION_TREE}
EXPECTED_EVALUATION_BRANCH=${EXPECTED_EVALUATION_BRANCH:?set EXPECTED_EVALUATION_BRANCH}

[[ "$FULL_OUTPUT_ROOT" == "$CHECKPOINT_ROOT/stability_capacity_full_300k_v1" ]]

PYTHON="$PYTHON" \
CHECKPOINT_ROOT="$CHECKPOINT_ROOT" \
FULL_OUTPUT_ROOT="$FULL_OUTPUT_ROOT" \
EXPECTED_FINAL_GATE_SHA256="$EXPECTED_FINAL_GATE_SHA256" \
EXPECTED_TARGET_REVISION="$EXPECTED_EVALUATION_REVISION" \
EXPECTED_TARGET_BRANCH="$EXPECTED_EVALUATION_BRANCH" \
bash "$FINALIZATION_PROJECT/artifacts/runbooks/generation_capacity_full_300k_export_inference_artifacts.sh"

AUDIT_PROJECT="$FINALIZATION_PROJECT" \
TRAINING_PROJECT="$TRAINING_PROJECT" \
FORMAL_PROJECT="$FORMAL_PROJECT" \
PYTHON="$PYTHON" \
CHECKPOINT_ROOT="$CHECKPOINT_ROOT" \
SOURCE_OUTPUT_ROOT="$SOURCE_OUTPUT_ROOT" \
FULL_OUTPUT_ROOT="$FULL_OUTPUT_ROOT" \
EXPECTED_TRAINING_SUPERVISOR_DEPLOYMENT_SHA256="$EXPECTED_TRAINING_SUPERVISOR_DEPLOYMENT_SHA256" \
EXPECTED_POSTEVAL_SUPERVISOR_DEPLOYMENT_SHA256="$EXPECTED_POSTEVAL_SUPERVISOR_DEPLOYMENT_SHA256" \
EXPECTED_TRAINING_LAUNCH_RECEIPT_SHA256="$EXPECTED_TRAINING_LAUNCH_RECEIPT_SHA256" \
EXPECTED_FINAL_GATE_SHA256="$EXPECTED_FINAL_GATE_SHA256" \
EXPECTED_TRAINING_REVISION="$EXPECTED_TRAINING_REVISION" \
EXPECTED_TRAINING_TREE="$EXPECTED_TRAINING_TREE" \
EXPECTED_TRAINING_BRANCH="$EXPECTED_TRAINING_BRANCH" \
EXPECTED_EVALUATION_REVISION="$EXPECTED_EVALUATION_REVISION" \
EXPECTED_EVALUATION_TREE="$EXPECTED_EVALUATION_TREE" \
EXPECTED_EVALUATION_BRANCH="$EXPECTED_EVALUATION_BRANCH" \
EXPECTED_EXPORT_REVISION="$EXPECTED_EVALUATION_REVISION" \
EXPECTED_EXPORT_BRANCH="$EXPECTED_EVALUATION_BRANCH" \
bash "$FINALIZATION_PROJECT/artifacts/runbooks/generation_capacity_full_300k_completion_audit.sh"
