#!/usr/bin/env bash
set -euo pipefail

PROJECT=${PROJECT:?set PROJECT to the exact capacity-completion execution checkout}
DECISION_PROJECT=${DECISION_PROJECT:?set DECISION_PROJECT}
TRAINING_PROJECT=${TRAINING_PROJECT:?set TRAINING_PROJECT}
PYTHON=${PYTHON:-/root/autodl-tmp/conda/envs/pf-vlm/bin/python}
CHECKPOINT_ROOT=${CHECKPOINT_ROOT:-/root/autodl-tmp/CoFiTok/checkpoints/generation}
STANDING_AUTHORIZATION=${STANDING_AUTHORIZATION:?set STANDING_AUTHORIZATION}
EXPECTED_STANDING_AUTHORIZATION_SHA256=${EXPECTED_STANDING_AUTHORIZATION_SHA256:?set EXPECTED_STANDING_AUTHORIZATION_SHA256}
EXPECTED_EXECUTION_REVISION=${EXPECTED_EXECUTION_REVISION:?set EXPECTED_EXECUTION_REVISION}
EXPECTED_EXECUTION_TREE=${EXPECTED_EXECUTION_TREE:?set EXPECTED_EXECUTION_TREE}
EXPECTED_EXECUTION_BRANCH=${EXPECTED_EXECUTION_BRANCH:?set EXPECTED_EXECUTION_BRANCH}
EXPECTED_DECISION_REVISION=${EXPECTED_DECISION_REVISION:?set EXPECTED_DECISION_REVISION}
EXPECTED_DECISION_TREE=${EXPECTED_DECISION_TREE:?set EXPECTED_DECISION_TREE}
EXPECTED_DECISION_BRANCH=${EXPECTED_DECISION_BRANCH:?set EXPECTED_DECISION_BRANCH}
EXPECTED_SCALING_DECISION_REVISION=${EXPECTED_SCALING_DECISION_REVISION:?set EXPECTED_SCALING_DECISION_REVISION}
EXPECTED_SCALING_DECISION_BRANCH=${EXPECTED_SCALING_DECISION_BRANCH:?set EXPECTED_SCALING_DECISION_BRANCH}
EXPECTED_SCALING_EXECUTION_REVISION=${EXPECTED_SCALING_EXECUTION_REVISION:?set EXPECTED_SCALING_EXECUTION_REVISION}
EXPECTED_SCALING_EXECUTION_TREE=${EXPECTED_SCALING_EXECUTION_TREE:?set EXPECTED_SCALING_EXECUTION_TREE}
EXPECTED_SCALING_EXECUTION_BRANCH=${EXPECTED_SCALING_EXECUTION_BRANCH:?set EXPECTED_SCALING_EXECUTION_BRANCH}
EXPECTED_TRAINING_REVISION=${EXPECTED_TRAINING_REVISION:?set EXPECTED_TRAINING_REVISION}
EXPECTED_TRAINING_TREE=${EXPECTED_TRAINING_TREE:?set EXPECTED_TRAINING_TREE}
EXPECTED_TRAINING_BRANCH=${EXPECTED_TRAINING_BRANCH:?set EXPECTED_TRAINING_BRANCH}
POLL_SECONDS=${POLL_SECONDS:-60}
REQUIRED_IDLE_POLLS=${REQUIRED_IDLE_POLLS:-5}
MAX_ATTEMPTS=${MAX_ATTEMPTS:-4}
RETRY_SECONDS=${RETRY_SECONDS:-120}
STALL_SECONDS=${STALL_SECONDS:-1800}
TERMINATION_GRACE_SECONDS=${TERMINATION_GRACE_SECONDS:-60}
TIMEOUT_SECONDS=${TIMEOUT_SECONDS:-10368000}

OUTPUT_ROOT="$CHECKPOINT_ROOT/stability_full_data_100k_capacity_probe_250m_10k_v1"
REPORT_ROOT="$OUTPUT_ROOT/reports"
DECISION_WAITER_STATUS="$REPORT_ROOT/capacity_completion_100k_decision_waiter_status.json"
DECISION="$REPORT_ROOT/capacity_completion_100k_decision.json"
SCALING_RESULT="$REPORT_ROOT/capacity_scaling_50k_result.json"
STATUS="$REPORT_ROOT/capacity_completion_100k_supervisor_status.json"
CHILD_LOG="$REPORT_ROOT/capacity_completion_100k_child.log"
RUNBOOK="$PROJECT/artifacts/runbooks/generation_capacity_completion_250m_100k_execute.sh"

cd "$PROJECT"
export PYTHONPATH="$PROJECT:$PROJECT/src${PYTHONPATH:+:$PYTHONPATH}"
exec "$PYTHON" scripts/run_generation_capacity_completion_100k_supervisor.py \
  --project "$PROJECT" \
  --decision-project "$DECISION_PROJECT" \
  --training-project "$TRAINING_PROJECT" \
  --decision-waiter-status "$DECISION_WAITER_STATUS" \
  --decision "$DECISION" \
  --scaling-result "$SCALING_RESULT" \
  --runbook "$RUNBOOK" \
  --standing-authorization "$STANDING_AUTHORIZATION" \
  --expected-standing-authorization-sha256 "$EXPECTED_STANDING_AUTHORIZATION_SHA256" \
  --checkpoint-root "$CHECKPOINT_ROOT" \
  --output-root "$OUTPUT_ROOT" \
  --status-output "$STATUS" \
  --child-log "$CHILD_LOG" \
  --expected-execution-revision "$EXPECTED_EXECUTION_REVISION" \
  --expected-execution-tree "$EXPECTED_EXECUTION_TREE" \
  --expected-execution-branch "$EXPECTED_EXECUTION_BRANCH" \
  --expected-decision-revision "$EXPECTED_DECISION_REVISION" \
  --expected-decision-tree "$EXPECTED_DECISION_TREE" \
  --expected-decision-branch "$EXPECTED_DECISION_BRANCH" \
  --expected-scaling-decision-revision "$EXPECTED_SCALING_DECISION_REVISION" \
  --expected-scaling-decision-branch "$EXPECTED_SCALING_DECISION_BRANCH" \
  --expected-scaling-execution-revision "$EXPECTED_SCALING_EXECUTION_REVISION" \
  --expected-scaling-execution-tree "$EXPECTED_SCALING_EXECUTION_TREE" \
  --expected-scaling-execution-branch "$EXPECTED_SCALING_EXECUTION_BRANCH" \
  --expected-training-revision "$EXPECTED_TRAINING_REVISION" \
  --expected-training-tree "$EXPECTED_TRAINING_TREE" \
  --expected-training-branch "$EXPECTED_TRAINING_BRANCH" \
  --poll-seconds "$POLL_SECONDS" \
  --required-idle-polls "$REQUIRED_IDLE_POLLS" \
  --max-attempts "$MAX_ATTEMPTS" \
  --retry-seconds "$RETRY_SECONDS" \
  --stall-seconds "$STALL_SECONDS" \
  --termination-grace-seconds "$TERMINATION_GRACE_SECONDS" \
  --timeout-seconds "$TIMEOUT_SECONDS"
